meta_product_name: "Travlr"
meta_title: "Travlr - Plan a trip with your friends!"
meta_description: "Travlr is a platform to plan trips with your friends. No more hassle keeping track of long email-chains, with Travlr it's all in one place!"
meta_image: "../app/assets/images/.web_friends_thumb.bpm" # should exist in `app/assets/images/`
twitter_account: "@travlr_twitter_account"   # required for Twitter Cards
